# Site settings
title: dvlprliu
email: dvlprliu@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dvlprliu.github.io" # the base hostname & protocol for your site
local_url: "http://127.0.0.1:4000/"
twitter_username: dvlprliu
github_username:  dvlprliu

# Build settings
markdown: kramdown
